version: "3.9"

services:
  app:
    build: .
    image: actility/tpxle-nit:0.0.1
    container_name: tpxle_nit_app

    ## volumes:

    working_dir: /opt/tpxle-nit/src

    environment:
      ############################################
      ## REDIS CONFIG
      ############################################
      NIT__REDIS_HOST: "redis"
      NIT__REDIS_PORT: "6379"

      ############################################
      ## MQTT BROKER CONFIG
      ############################################
      NIT__MQTT_ENABLED: "True"
      # NIT__BROKER_URL: "mqtt://localhost:1883"
      NIT__BROKER_URL: "mqtts://mqtt.preview.thingpark.com:8883"
      # NIT__CA_CERT_LOCATION: ""

      ############################################
      ## The following sensitive parameters are set in the .env
      ## file that is part of .gitignore
      ############################################
      # NIT__MQTT_SUPER_USER: ""
      # NIT__MQTT_SUPER_PASSWD: ""

      NIT__SERVER_PORT: "8081"
      NIT__LOG_LEVEL: "debug"
      ## error | warn | info | http | verbose | debug | silly

      NIT__VALID_ARCHITECTURE_IDS: "ECOKC,ECODX,PREVKC,PREVDX,abeeway-mobile-app,dev1,le-lab,rnd"
      ## abeeway-mobile-app, dev1, le-lab, rnd are added for backward compatibility
      NIT__DEFAULT_REALM: "ECODX"

      ############################################
      ## Ecosystem_TPXLE with Ecosystem_Keycloak
      ############################################
      NIT__ECOKC_SWAGGER_UI: "https://abeeway-mobile-app-eco.thingpark.com/admin/latest/swagger-ui/index.html?shortUrl=tpdx-admin-api-contract.json"
      NIT__ECOKC_FEED_URL: "https://abeeway-mobile-app-eco.thingpark.com/location/latest/api/feeds"
      NIT__ECOKC_TOKEN_REQUEST_URL: "https://abeeway-mobile-app-eco.thingpark.com/auth"
      NIT__ECOKC_OPERATOR_ID: "actility-tpe-ope"
      NIT__ECOKC_GRANT_TYPE: "password"
      NIT__ECOKC_REALM: "abeeway-mobile-app"
      NIT__ECOKC_SCOPE: "openid"
      NIT__ECOKC_CLIENT_ID: "tpx-le-nit"

      ############################################
      ## Ecosystem_TPXLE with Ecosystem_DxAdminAPI
      ############################################
      NIT__ECODX_SWAGGER_UI: "https://dx-api.thingpark.io/admin/latest/swagger-ui/index.html?shortUrl=tpdx-admin-api-contract.json"
      NIT__ECODX_FEED_URL: "https://dx-api.thingpark.io/location/latest/api/feeds"
      NIT__ECODX_TOKEN_REQUEST_URL: "https://dx-api.thingpark.io/admin/latest/api/oauth/token"
      NIT__ECODX_OPERATOR_ID: "actility-tpe-ope"
      NIT__ECODX_GRANT_TYPE: "client_credentials"

      ############################################
      ## Preview_TPXLE with Preview_Keycloak
      ############################################
      NIT__PREVKC_SWAGGER_UI: "https://le-lab.preview.thingpark.com/admin/latest/swagger-ui/index.html?shortUrl=tpdx-admin-api-contract.json"
      NIT__PREVKC_FEED_URL: "https://le-lab.preview.thingpark.com/location/latest/api/feeds"
      NIT__PREVKC_TOKEN_REQUEST_URL: "https://le-lab.preview.thingpark.com/auth"
      NIT__PREVKC_OPERATOR_ID: "dev-ope"
      NIT__PREVKC_GRANT_TYPE: "password"
      NIT__PREVKC_REALM: "le-lab"
      NIT__PREVKC_SCOPE: "openid"
      NIT__PREVKC_CLIENT_ID: "tpx-le-nit"

      ############################################
      ## Preview_TPXLE with Preview_DxAdminAPI
      ############################################
      NIT__PREVDX_SWAGGER_UI: "https://dx-api.preview.thingpark.com/admin/latest/swagger-ui/index.html?shortUrl=tpdx-admin-api-contract.json"
      NIT__PREVDX_FEED_URL: "https://dx-api.preview.thingpark.com/location/latest/api/feeds"
      NIT__PREVDX_TOKEN_REQUEST_URL: "https://dx-api.preview.thingpark.com/admin/latest/api/oauth/token"
      NIT__PREVDX_OPERATOR_ID: "dev-ope"
      NIT__PREVDX_GRANT_TYPE: "client_credentials"

    #########################
    ## FOR DEVELOPMENT
    #########################
    # entrypoint: ["tail"]
    # command: ["-f","/dev/null"]

    ports:
      - 8081:8081

  redis:
    image: redis:alpine
    container_name: tpxle_nit_redis
#    volumes:
#      - ./redis-data:/data
#    ports:
#      - 6379:6379
