NIT_SERVER_PORT: 8081
REDIS_HOST: "redis"
REDIS_PORT: 6379
LOG_LEVEL: debug # error | warn | info | http | verbose | debug | silly

# binder module (swagger)
# https://dx-api.thingpark.io/location/latest/swagger-ui/index.html?shortUrl=tpdx-location-api-contract.json#/Feed/post_feeds

# DEV1_REALM: dev1 # used for Ecosystem_TPXLE and Ecosystem_DxAdminAPI
# DEV1_FEED_URL: "https://dx-api.thingpark.io/location/latest/api/feeds"
# DEV1_TOKEN_REQUEST_URL: "https://dx-api.thingpark.io/admin/latest/api/oauth/token"
# DEV1_GRANT_TYPE: "client_credentials"
# DEV1_CLIENT_ID: # x-client-id
# DEV1_CLIENT_SECRET: # x-client-secret

# binder module (swagger)
# https://le-lab.preview.thingpark.com/location/latest/swagger-ui/index.html?shortUrl=tpdx-location-api-contract.json#/Feed/post_feeds

# LELAB_REALM: "le-lab" # x-realm  # used for R&D_TPXLE and R&D_Keycloak
# LELAB_FEED_URL: "https://le-lab.preview.thingpark.com/location/latest/api/feeds"
# LELAB_TOKEN_REQUEST_URL: "https://le-lab.preview.thingpark.com/auth"
# LELAB_GRANT_TYPE: "password"
# LELAB_SCOPE: "openid"
# LELAB_CLIENT_ID: "tpx-le-nit"
# LELAB_USERNAME: # x-client-id
# LELAB_PASSWORD: # x-client-secret

# LELAB1_REALM: "le-lab1" # x-realm # used for R&D_TPXLE and R&D_DxAdminAPI
# LELAB1_FEED_URL: "https://le-lab.preview.thingpark.com/location/latest/api/feeds"
# LELAB1_TOKEN_REQUEST_URL: "https://le-lab.preview.thingpark.com/admin/latest/api/oauth/token"
# LELAB1_GRANT_TYPE: "client_credentials"

VALID_REALMS:
  - dev1
  - le-lab
  - le-lab1

DEFAULT_REALM: dev1

dev1:
  REALM: dev1 # used for Ecosystem_TPXLE with Ecosystem_DxAdminAPI
  FEED_URL: "https://dx-api.thingpark.io/location/latest/api/feeds"
  TOKEN_REQUEST_URL: "https://dx-api.thingpark.io/admin/latest/api/oauth/token"
  GRANT_TYPE: "client_credentials"

le-lab: # x-realm  # used for R&D_TPXLE with R&D_Keycloak
  FEED_URL: "https://le-lab.preview.thingpark.com/location/latest/api/feeds"
  TOKEN_REQUEST_URL: "https://le-lab.preview.thingpark.com/auth"
  GRANT_TYPE: "password"
  SCOPE: "openid"
  CLIENT_ID: "tpx-le-nit"

le-lab1: # x-realm # used for R&D_TPXLE with R&D_DxAdminAPI
  FEED_URL: "https://le-lab.preview.thingpark.com/location/latest/api/feeds"
  TOKEN_REQUEST_URL: "https://le-lab.preview.thingpark.com/admin/latest/api/oauth/token"
  GRANT_TYPE: "client_credentials"
